function openService(id){activeService=byId(id);document.getElementById('serviceModalCategory').textContent=activeService.category;document.getElementById('serviceModalTitle').textContent=activeService.title;document.getElementById('serviceModalDescription').textContent=activeService.description;document.getElementById('serviceModalPrice').textContent=`${euro(activeService.price)} · ${activeService.unit}`;openModal('serviceModal')}
    function openModal(id){document.getElementById(id).classList.add('open');document.body.style.overflow='hidden';setTimeout(()=>document.getElementById(id).querySelector('button,input')?.focus(),30)}
    function closeModals(){document.querySelectorAll('.modal-backdrop').forEach(m=>m.classList.remove('open'));document.body.style.overflow=''}
    function showToast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
    function totals(){const subtotal=[...cart].reduce((sum,[id,q])=>sum+byId(id).price*q,0);const discount=subtotal>=1000?Math.round(subtotal*.1):0;return{subtotal,discount,total:subtotal-discount}}
    function requestText(){const name=document.getElementById('clientName')?.value.trim()||'—';const contact=document.getElementById('clientContact')?.value.trim()||'—';const idea=document.getElementById('clientIdea')?.value.trim()||'—';const lines=cart.size?[...cart].map(([id,q])=>`• ${byId(id).title} × ${q} — ${euro(byId(id).price*q)}`):['• Нужна консультация и помощь с выбором услуг'];const t=totals();return `ЗАЯВКА В SYNAIRGY RECORD’S\n\nИмя: ${name}\nКонтакт: ${contact}\n\nИдея / задача:\n${idea}\n\nВыбранные услуги:\n${lines.join('\n')}\n\nОриентировочная стоимость: ${euro(t.total)}${t.discount?` (включая скидку ${euro(t.discount)})`:''}\n\nХочу обсудить детали, сроки и финальную смету.`}
    function updateRequestPreview(){const p=document.getElementById('requestPreview');if(p)p.textContent=requestText()}
    async function copyRequest(){try{await navigator.clipboard.writeText(requestText());showToast('Заявка скопирована')}catch{const ta=document.createElement('textarea');ta.value=requestText();document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();showToast('Заявка скопирована')}}
    async function shareRequest(){if(navigator.share){try{await navigator.share({title:'Заявка в SynAirgy Record’s',text:requestText()})}catch(e){}}else{await copyRequest();showToast('Скопировано — вставь сообщение в мессенджер')}}

    document.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]')||e.target.classList.contains('modal-backdrop'))closeModals()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModals()});
    document.getElementById('modalAddService').onclick=()=>{if(activeService)addService(activeService.id);closeModals()};
    document.querySelectorAll('[data-open-order]').forEach(b=>b.onclick=()=>{updateRequestPreview();openModal('orderModal')});
    document.querySelectorAll('[data-consult]').forEach(b=>b.onclick=()=>{cart.set('consult',1);saveCart();renderServices();renderCart();openModal('orderModal')});
    document.getElementById('orderFromCalc').onclick=()=>{updateRequestPreview();openModal('orderModal')};
    ['clientName','clientContact','clientIdea'].forEach(id=>document.getElementById(id).addEventListener('input',updateRequestPreview));document.getElementById('copyRequest').onclick=copyRequest;document.getElementById('shareRequest').onclick=shareRequest;
    document.getElementById('micTabs').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;activeMicGroup=b.dataset.group;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));renderMics()});document.getElementById('micSearch').addEventListener('input',renderMics);
    document.getElementById('micSwitches').addEventListener('click',e=>{const b=e.target.closest('[data-lab]');if(b)setLab(b.dataset.lab)});
    const menuBtn=document.getElementById('menuBtn'),mobileMenu=document.getElementById('mobileMenu');menuBtn.onclick=()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open);menuBtn.textContent=open?'×':'☰'};mobileMenu.querySelectorAll('a').forEach(a=>a.onclick=()=>{mobileMenu.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');menuBtn.textContent='☰'});
    document.getElementById('year').textContent=new Date().getFullYear();
    renderWave();renderServices();renderCart();renderPackages();renderGear();renderMics();setLab('u47');updateRequestPreview();
