const iconSvgs = {
      interface:`<svg viewBox="0 0 120 90" aria-hidden="true"><rect x="11" y="17" width="98" height="58" rx="12" fill="#18241c" stroke="#5af25f"/><circle cx="40" cy="46" r="17" fill="#0a0f0c" stroke="#9cac9f"/><circle cx="40" cy="46" r="8" fill="#5af25f"/><rect x="66" y="30" width="29" height="8" rx="4" fill="#324c38"/><circle cx="72" cy="57" r="5" fill="#c8ff58"/><circle cx="88" cy="57" r="5" fill="#5af25f"/></svg>`,
      mic:`<svg viewBox="0 0 90 110" aria-hidden="true"><rect x="29" y="8" width="32" height="55" rx="15" fill="#27342b" stroke="#c8ff58"/><path d="M45 63v26M25 46c0 27 40 27 40 0M30 96h30" stroke="#5af25f" stroke-width="4" fill="none"/><path d="M34 20h22M33 29h24M33 38h24" stroke="#839087"/></svg>`,
      preamp:`<svg viewBox="0 0 110 90"><rect x="8" y="14" width="94" height="62" rx="9" fill="#151f18" stroke="#4f7758"/><circle cx="30" cy="45" r="15" fill="#070b08" stroke="#c8ff58"/><path d="M30 30v15l10 5" stroke="#5af25f" stroke-width="3"/><rect x="58" y="27" width="28" height="5" rx="2" fill="#5af25f"/><rect x="58" y="41" width="20" height="5" rx="2" fill="#6c7d71"/><rect x="58" y="55" width="32" height="5" rx="2" fill="#6c7d71"/></svg>`,
      speaker:`<svg viewBox="0 0 90 110"><rect x="17" y="6" width="56" height="96" rx="8" fill="#172119" stroke="#4c6c53"/><circle cx="45" cy="65" r="22" fill="#070a08" stroke="#7b8b80"/><circle cx="45" cy="65" r="8" fill="#5af25f"/><circle cx="45" cy="27" r="8" fill="#070a08" stroke="#c8ff58"/></svg>`,
      headphones:`<svg viewBox="0 0 110 90"><path d="M20 50c0-45 70-45 70 0" fill="none" stroke="#5af25f" stroke-width="8"/><rect x="12" y="46" width="22" height="34" rx="9" fill="#1b281e" stroke="#c8ff58"/><rect x="76" y="46" width="22" height="34" rx="9" fill="#1b281e" stroke="#c8ff58"/><path d="M87 78c0 8-8 8-17 8" fill="none" stroke="#5af25f" stroke-width="3"/></svg>`,
      plugin:`<svg viewBox="0 0 120 90"><rect x="6" y="10" width="108" height="70" rx="9" fill="#111a14" stroke="#4e6c54"/><rect x="15" y="20" width="45" height="50" rx="7" fill="#071009"/><circle cx="37" cy="43" r="13" fill="#18281d" stroke="#5af25f"/><path d="M37 30v13l8 4" stroke="#c8ff58" stroke-width="3"/><path d="M70 29h31M70 42h24M70 55h34" stroke="#5af25f" stroke-width="5" stroke-linecap="round"/></svg>`,
      compressor:`<svg viewBox="0 0 120 90"><rect x="5" y="12" width="110" height="66" rx="8" fill="#192119" stroke="#69786c"/><rect x="16" y="23" width="48" height="26" rx="4" fill="#efe8ca"/><path d="M23 44c10-18 23-18 34 0" fill="none" stroke="#313b33"/><path d="M40 43l10-12" stroke="#d34f40" stroke-width="2"/><circle cx="80" cy="39" r="11" fill="#0b100c" stroke="#c8ff58"/><circle cx="100" cy="39" r="7" fill="#0b100c" stroke="#5af25f"/><path d="M18 62h83" stroke="#4b5d50" stroke-width="4"/></svg>`,
      daw:`<svg viewBox="0 0 120 90"><rect x="7" y="8" width="106" height="74" rx="8" fill="#121b15" stroke="#4f7356"/><path d="M16 24h88M36 16v58" stroke="#344c39"/><path d="M44 34h50M44 45h35M44 56h58" stroke="#5af25f" stroke-width="5"/><rect x="15" y="32" width="14" height="9" rx="2" fill="#c8ff58"/><rect x="15" y="48" width="14" height="9" rx="2" fill="#5af25f"/></svg>`,
      collection:`<svg viewBox="0 0 120 90"><path d="M20 71V31c0-15 20-15 20 0v40M50 71V18c0-15 20-15 20 0v53M80 71V38c0-15 20-15 20 0v33" fill="#172219" stroke="#5af25f" stroke-width="3"/><path d="M13 71h94" stroke="#c8ff58" stroke-width="4"/></svg>`,
      chain:`<svg viewBox="0 0 120 90"><path d="M45 28l-9-9c-10-10-26 6-16 16l13 13c7 7 17 7 24 0l9-9M75 62l9 9c10 10 26-6 16-16L87 42c-7-7-17-7-24 0l-9 9" fill="none" stroke="#5af25f" stroke-width="7" stroke-linecap="round"/><path d="M43 57l34-34" stroke="#c8ff58" stroke-width="6" stroke-linecap="round"/></svg>`
    };

    const cart = new Map(JSON.parse(localStorage.getItem('synairgyCart') || '[]'));
    let activeService = null;
    let activeMicGroup = 'all';

    const euro = n => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
    const byId = id => services.find(s=>s.id===id);
    const saveCart = () => localStorage.setItem('synairgyCart',JSON.stringify([...cart]));

    function renderWave(){const w=document.getElementById('heroWave');for(let i=0;i<62;i++){const s=document.createElement('span');s.style.height=(12+Math.random()*80)+'%';w.appendChild(s)}}
    function renderServices(){
      const grid=document.getElementById('serviceGrid');
      grid.innerHTML=services.map(s=>`<article class="service-card" data-service="${s.id}" tabindex="0" role="button" aria-label="Подробнее: ${s.title}">${s.popular?'<span class="popular-flag">Популярно</span>':''}<div class="service-top"><span class="service-icon">${s.icon}</span><span class="muted" style="font-size:.7rem">${s.category}</span></div><h3>${s.title}</h3><p>${s.short}</p><footer><div class="price">${euro(s.price)}<span class="unit">${s.unit}</span></div><button class="add-circle ${cart.has(s.id)?'added':''}" data-add="${s.id}" aria-label="Добавить ${s.title}">${cart.has(s.id)?'✓':'+'}</button></footer></article>`).join('');
      grid.querySelectorAll('.service-card').forEach(card=>{card.addEventListener('click',e=>{if(e.target.closest('[data-add]'))return;openService(card.dataset.service)});card.addEventListener('keydown',e=>{if(e.key==='Enter')openService(card.dataset.service)})});
      grid.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();toggleService(btn.dataset.add)}));
    }
    function toggleService(id){cart.has(id)?cart.delete(id):cart.set(id,1);saveCart();renderServices();renderCart();showToast(cart.has(id)?'Добавлено в проект':'Удалено из проекта')}
    function addService(id){cart.set(id,(cart.get(id)||0)+1);saveCart();renderServices();renderCart();showToast('Добавлено в проект')}
    function renderCart(){
      const host=document.getElementById('cartList');
      if(!cart.size){host.innerHTML='<div class="cart-empty">Выбери услуги слева или примени готовый пакет.</div>'}else{
        host.innerHTML='<div class="cart-list">'+[...cart].map(([id,qty])=>{const s=byId(id);return `<div class="cart-item"><div class="cart-main"><span class="cart-name">${s.title}</span><span class="cart-line-price">${euro(s.price*qty)}</span></div><div class="cart-controls"><div class="qty"><button data-minus="${id}" aria-label="Уменьшить">−</button><span>${qty}</span><button data-plus="${id}" aria-label="Увеличить">+</button></div><button class="remove" data-remove="${id}" aria-label="Удалить">×</button></div></div>`}).join('')+'</div>';
        host.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));host.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.delete(b.dataset.remove);saveCart();renderServices();renderCart()});
      }
      const subtotal=[...cart].reduce((sum,[id,q])=>sum+byId(id).price*q,0);const discount=subtotal>=1000?Math.round(subtotal*.1):0;const total=subtotal-discount;
      document.getElementById('subtotal').textContent=euro(subtotal);document.getElementById('discount').textContent='−'+euro(discount);document.getElementById('discountRow').hidden=!discount;document.getElementById('total').textContent=euro(total);updateRequestPreview();
    }
    function changeQty(id,delta){const next=(cart.get(id)||0)+delta;if(next<=0)cart.delete(id);else cart.set(id,next);saveCart();renderServices();renderCart()}
    function renderPackages(){document.getElementById('packageGrid').innerHTML=packages.map((p,i)=>`<article class="package ${i===1?'featured':''}">${p.badge?`<span class="package-badge">${p.badge}</span>`:''}<div class="package-head"><h3>${p.name}</h3><div class="package-price">${euro(p.price)}</div></div><ul>${p.items.map(x=>`<li>${x}</li>`).join('')}</ul><button class="btn ${i===1?'btn-primary':'btn-ghost'}" data-package="${i}">Выбрать пакет →</button></article>`).join('');document.querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>applyPackage(+b.dataset.package))}
    function applyPackage(i){cart.clear();packages[i].cart.forEach(([id,q])=>cart.set(id,q));saveCart();renderServices();renderCart();document.getElementById('services').scrollIntoView({behavior:'smooth'});showToast('Пакет добавлен в калькулятор')}
    function renderGear(){document.getElementById('gearGrid').innerHTML=gear.map(g=>`<article class="gear-card"><span class="gear-glow"></span><div class="gear-visual">${iconSvgs[g.icon]}</div><div><h3>${g.title}</h3><p>${g.text}</p></div></article>`).join('')}
    function renderMics(){const q=document.getElementById('micSearch').value.trim().toLowerCase();const filtered=microphones.filter(([name,group,type])=>(activeMicGroup==='all'||group===activeMicGroup)&&(`${name} ${type}`).toLowerCase().includes(q));document.getElementById('micList').innerHTML=filtered.map(([name,group,type])=>`<div class="mic-pill">${name}<small>${group==='main'?'Sphere Mic Collection':group==='putnam'?'Bill Putnam Collection':'Ocean Way Collection'} · ${type}</small></div>`).join('');document.getElementById('noResults').style.display=filtered.length?'none':'block'}
    function renderSpectrum(values){const s=document.getElementById('spectrum');s.innerHTML=values.map(v=>`<span style="height:${v}%"></span>`).join('')}
    const lab={u47:{title:'Neumann U47 — большой, плотный, кинематографичный',text:'Хорош для голоса, которому нужен вес, мягкая середина и ощущение дорогой классической записи.',bars:[38,44,53,68,79,88,91,86,74,66,61,56,52,46,42,39]},c800:{title:'Sony C-800G — яркий, быстрый, современный',text:'Частый ориентир для pop и hip-hop: много присутствия, воздуха и читаемости поверх плотного бита.',bars:[31,36,42,51,58,65,71,78,85,92,96,91,84,77,69,61]},u87:{title:'Neumann U87 Ai — ровный студийный стандарт',text:'Предсказуемый баланс и собранная середина. Хорошая точка отсчёта для речи, вокала и универсальных задач.',bars:[43,48,53,57,61,64,67,69,71,74,76,73,68,62,56,49]},251:{title:'Telefunken ELA M 251 — воздушный и музыкальный',text:'Широкий, живой верх без ощущения дешёвой резкости. Красиво работает на эмоциональном вокале и бэках.',bars:[35,42,50,61,69,77,84,89,94,97,94,88,80,73,65,57]}};
    function setLab(id){document.querySelectorAll('.mic-switch').forEach(b=>b.classList.toggle('active',b.dataset.lab===id));document.getElementById('labTitle').textContent=lab[id].title;document.getElementById('labText').textContent=lab[id].text;renderSpectrum(lab[id].bars)}
