const services = [
      {id:'consult',icon:'◌',title:'Консультация и разбор идеи',short:'Разбираем цель, референсы и реальный маршрут проекта.',description:'Созвон или встреча, на которой превращаем расплывчатую идею в понятный план: формат релиза, стиль, этапы, сроки и ориентировочный бюджет. Подходит даже если есть только одна фраза или настроение.',price:49,unit:'сессия',category:'Подготовка'},
      {id:'reference',icon:'◎',title:'Подбор референсов и направления',short:'Ищем точный жанровый и эмоциональный вектор.',description:'Собираем несколько музыкальных ориентиров, разбираем темп, форму, вокальную подачу, плотность бита и общее ощущение. Итог — ясное техническое и творческое направление для всей команды.',price:79,unit:'проект',category:'Подготовка'},
      {id:'lyrics',icon:'✎',title:'Текст и драматургия',short:'Куплеты, припев, хук и структура истории.',description:'Помогаем написать текст с нуля или довести черновик: смысл, ритмика, рифмовка, хук, форма и удобство исполнения. Авторские доли согласуются до начала работы.',price:120,unit:'от',category:'Создание'},
      {id:'topline',icon:'♪',title:'Мелодия / topline',short:'Вокальная мелодия, хук и варианты подачи.',description:'Создаём оригинальную вокальную мелодию под готовый бит или вместе с продакшном. Записываем демо, подбираем диапазон и строим форму так, чтобы исполнитель мог уверенно подать материал.',price:150,unit:'от',category:'Создание'},
      {id:'beat',icon:'▦',title:'Авторский бит / продакшн',short:'Оригинальная музыка под исполнителя и задачу.',description:'Создаём бит и саунд-дизайн с нуля: гармония, ударные, бас, синтезаторы, переходы и динамика. Можно работать вокруг референса, но без копирования защищённой мелодии, текста, сэмпла или мастер-записи.',price:350,unit:'от',category:'Продакшн',popular:true},
      {id:'reference-production',icon:'≈',title:'Референс-продакшн',short:'Похожее ощущение — новая оригинальная композиция.',description:'Передаём настроение, темп, жанровую механику и энергетику выбранного трека, но создаём новую мелодию, гармонию, аранжировку и звук. Перед релизом отдельно проверяем источники сэмплов и права на сторонние материалы.',price:450,unit:'от',category:'Продакшн'},
      {id:'arrangement',icon:'⌘',title:'Аранжировка',short:'Развитие песни, переходы, кульминация и детали.',description:'Превращаем демо или петлю в полноценный трек: интро, куплеты, припевы, бридж, дропы, дополнительные партии и автоматизации. Работаем с уже существующим материалом или с нашим продакшном.',price:220,unit:'от',category:'Продакшн'},
      {id:'recording',icon:'◉',title:'Вокальная запись',short:'Профессиональная сессия с вокальной режиссурой.',description:'Запись в студии с контролем уровня, артикуляции, дыхания, эмоции и дублей. Включает оперативный подбор микрофонного характера Sphere и базовую организацию сессии.',price:60,unit:'час',category:'Запись',popular:true},
      {id:'vocal-production',icon:'⌁',title:'Vocal production',short:'Компинг, даблы, бэки, эдлибы и структура вокала.',description:'Собираем сильный основной дубль, выстраиваем даблы, бэк-вокалы и эдлибы, решаем где нужен воздух, плотность или пауза. Это мост между просто записью и готовым вокальным продакшном.',price:110,unit:'трек',category:'Запись'},
      {id:'editing',icon:'✣',title:'Тюнинг и редактура вокала',short:'Высота, тайминг, шумы, дыхание и чистота монтажа.',description:'Ручная коррекция интонации и тайминга без пластикового эффекта, если он не нужен. Чистим щелчки, лишние шумы, неудачные вдохи и делаем вокал технически готовым к сведению.',price:90,unit:'трек',category:'Постпродакшн',popular:true},
      {id:'mixing',icon:'☷',title:'Сведение',short:'Баланс, глубина, энергия и единый характер трека.',description:'Полноценное сведение: баланс, эквализация, компрессия, сатурация, пространство, автоматизации, работа с вокалом и переводимость на разные системы. Включены две серии правок.',price:250,unit:'от / трек',category:'Постпродакшн',popular:true},
      {id:'mastering',icon:'◇',title:'Мастеринг',short:'Финальная громкость и готовность к площадкам.',description:'Финальная обработка готового микса: тональный баланс, динамика, стерео, контроль пиков и подготовка файлов для цифрового релиза. Включён основной master и instrumental master при наличии.',price:80,unit:'трек',category:'Постпродакшн'},
      {id:'cover',icon:'▣',title:'Обложка релиза',short:'Визуальная идея и адаптация под платформы.',description:'Концепция и дизайн single/EP cover с экспортом в необходимых размерах. Сложные фотосъёмки, 3D и дополнительные форматы рассчитываются отдельно.',price:120,unit:'от',category:'Визуал'},
      {id:'metadata',icon:'≡',title:'Metadata / ISRC / credits',short:'Авторы, исполнители, версии и данные релиза.',description:'Собираем и проверяем метаданные, credits, названия версий, даты, explicit-метки, авторов и исполнителей. ISRC оформляется через выбранного дистрибьютора или лейбловый процесс.',price:75,unit:'релиз',category:'Публикация'},
      {id:'distribution',icon:'↗',title:'Дистрибуция и публикация',short:'Подготовка и загрузка релиза на площадки.',description:'Готовим пакет файлов и размещаем релиз через согласованного дистрибьютора. Проверяем обложку, метаданные, даты, профили артистов и статус доставки. Подписка или комиссия самого дистрибьютора оплачивается отдельно, если требуется.',price:60,unit:'релиз',category:'Публикация',popular:true},
      {id:'rights',icon:'⚖',title:'Правовой пакет релиза',short:'Split sheet, права, сэмплы и документы проекта.',description:'Фиксируем роли и доли, оформляем split sheet, проверяем происхождение бита и сэмплов, разделяем права на композицию и мастер. Получение разрешений и отдельное юридическое представительство рассчитываются по ситуации.',price:180,unit:'от',category:'Права'},
      {id:'strategy',icon:'⌖',title:'Release strategy',short:'План выхода, контент и последовательность действий.',description:'Строим календарь релиза: тизеры, pre-save, вертикальный контент, день выхода, пост-релизные материалы и точки анализа. Без обещаний алгоритмического чуда — только понятная система действий.',price:180,unit:'релиз',category:'Продвижение'},
      {id:'reels',icon:'▤',title:'Съёмка и монтаж Reels',short:'Вертикальные видео для прогрева и поддержки трека.',description:'Концепция, съёмка и монтаж одного вертикального видео. Пакеты из нескольких роликов считаются выгоднее и могут быть сняты за один production day.',price:180,unit:'от / ролик',category:'Видео'},
      {id:'performance',icon:'▶',title:'Performance video',short:'Стильное видео вокруг исполнения трека.',description:'Камерное performance-видео или studio live: идея, свет, съёмка, монтаж и базовая цветокоррекция. Локации, актёры и сложная постановка рассчитываются отдельно.',price:350,unit:'от',category:'Видео'},
      {id:'music-video',icon:'◆',title:'Музыкальный клип',short:'Сценарий, препродакшн, съёмка и постпродакшн.',description:'Полный визуальный проект: идея, сценарий, shot list, организация съёмки, монтаж, цвет, титры и версии для соцсетей. Итоговая цена зависит от команды, техники, локаций и сложности постановки.',price:890,unit:'от',category:'Видео'}
    ];

    const packages = [
      {name:'FIRST PHRASE',price:149,badge:'',items:['Разбор идеи и референсов','1 час вокальной записи','Rough mix для оценки направления'],cart:[['consult',1],['recording',1]]},
      {name:'SINGLE READY',price:549,badge:'Популярный',items:['До 2 часов вокальной записи','Vocal production и редактура','Сведение','Мастеринг'],cart:[['recording',2],['vocal-production',1],['editing',1],['mixing',1],['mastering',1]]},
      {name:'FULL RELEASE',price:1290,badge:'',items:['Оригинальный продакшн и аранжировка','Запись и вокальная редактура','Сведение и мастеринг','Обложка, metadata и публикация','Release strategy'],cart:[['beat',1],['arrangement',1],['recording',2],['editing',1],['mixing',1],['mastering',1],['cover',1],['metadata',1],['distribution',1],['strategy',1]]}
    ];

    const gear = [
      {title:'Universal Audio Apollo Twin Duo USB',text:'Интерфейс, UAD DSP, стабильный мониторинг и работа через Console.',icon:'interface'},
      {title:'Universal Audio Sphere LX',text:'Двухкапсульная запись и моделирование классических микрофонных характеров.',icon:'mic'},
      {title:'Unison Preamps',text:'Предусилители и входная цепочка UAD в реальном времени.',icon:'preamp'},
      {title:'Adam Audio P11',text:'Основной контроль баланса, середины, стерео и глубины микса.',icon:'speaker'},
      {title:'Beyerdynamic DT1990 / DT770 Pro',text:'Открытый и закрытый контроль деталей, вокала и низких частот.',icon:'headphones'},
      {title:'UAD Vocal Suite + Vocal Tune',text:'Быстрая современная вокальная цепочка и точная коррекция.',icon:'plugin'},
      {title:'UAD Fairchild Collection',text:'Ламповая динамика, плотность, движение и музыкальный glue.',icon:'compressor'},
      {title:'Cubase Production',text:'Запись, MIDI, аранжировка, монтаж, сведение и финальные экспорты.',icon:'daw'},
      {title:'Sphere Mic Collections',text:'Основная, Bill Putnam и Ocean Way — десятки вариантов характера.',icon:'collection'},
      {title:'Controlled Recording Chain',text:'Сессия организована так, чтобы решения можно было менять без потери материала.',icon:'chain'}
    ];

    const microphones = [
      ['Neumann U47','main','ламповый'],['Neumann M49c','main','ламповый'],['Neumann U67 — 1960s','main','ламповый'],['Neumann U67 NOS — 1991 reissue','main','ламповый'],['Neumann U87 — Vintage 1970s','main','FET'],['Neumann U87 Ai','main','FET'],['Neumann U87 Tracy Korby Mod','main','модифицированный'],['Neumann TLM 103','main','FET'],['AKG C12','main','ламповый'],['Telefunken ELA M 251','main','ламповый'],['Sony C-800G','main','ламповый'],['Sony C-37A','main','ламповый'],['Sony C-37P','main','FET'],['Brauner VM1 Klaus Heyne Edition','main','ламповый'],['AKG C414 EB Brass CK12','main','конденсаторный'],['AKG C414 EB Nylon','main','конденсаторный'],['AKG C414 B-ULS','main','конденсаторный'],['AKG C414 B-TL II','main','конденсаторный'],['Neumann / Gefell CMV 563','main','ламповый'],['Soyuz SU-017 Tube','main','ламповый'],['AKG C451','main','малодиафрагменный'],['Sennheiser MKH 416','main','shotgun'],['Coles 4038','main','ленточный'],['RCA 77-DX Satin','main','ленточный'],['RCA 77-DX Umber','main','ленточный'],['Royer R-121','main','ленточный'],['Beyerdynamic M160','main','ленточный'],['Shure SM57','main','динамический'],['Shure SM7A','main','динамический'],['Electro-Voice RE20','main','динамический'],['Sennheiser MD409 — Early','main','динамический'],['Sennheiser MD409 — 1980s','main','динамический'],['Sennheiser MD421 — 1960s','main','динамический'],['Sennheiser MD421 Script Logo','main','динамический'],['Sennheiser MD421 Black','main','динамический'],['AKG D12 — 1950s','main','динамический'],['AKG D12E','main','динамический'],
      ['Telefunken ELA M 251E — US Export','putnam','Bill Putnam'],['Telefunken ELA M 251 — AC701k','putnam','Bill Putnam'],['Neumann U47 M7','putnam','Bill Putnam'],['Neumann U67 — Early 1960s','putnam','Bill Putnam'],['AKG C12A','putnam','Bill Putnam'],['Sony C-37A — Putnam specimen','putnam','Bill Putnam'],['Sennheiser MKH 405 / MKH 105','putnam','Bill Putnam'],['RCA 44BX','putnam','Bill Putnam'],['Shure 545 Unidyne III','putnam','Bill Putnam'],
      ['Neumann U47 — Allen Sides #2679','ocean','Ocean Way'],['AKG C12 #1','ocean','Ocean Way'],['AKG C12 #2 — warmer','ocean','Ocean Way'],['Neumann M49b','ocean','Ocean Way'],['Neumann M269','ocean','Ocean Way'],['Sony C-800G Prototype','ocean','Ocean Way'],['Neumann M50a','ocean','Ocean Way'],['Neumann KM53','ocean','Ocean Way'],['Neumann KM54','ocean','Ocean Way'],['Sony C-55P','ocean','Ocean Way'],['RCA KU-3A / 10001','ocean','Ocean Way'],['Shure SM57 Vintage USA','ocean','Ocean Way']
    ];
